"""Create user table

Revision ID: ee107c6b6201
Revises: 088588aa8097
Create Date: 2024-10-31 16:45:13.867521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee107c6b6201'
down_revision = '088588aa8097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert-list')
    op.drop_table('Alert_List')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alert_List',
    sa.Column('Name', sa.TEXT(), nullable=True),
    sa.Column('Address', sa.TEXT(), nullable=True),
    sa.Column('Website', sa.TEXT(), nullable=True),
    sa.Column('years', sa.INTEGER(), nullable=True),
    sa.Column('Remarks', sa.TEXT(), nullable=True),
    sa.Column('Telegram Group:', sa.TEXT(), nullable=True),
    sa.Column('field7', sa.TEXT(), nullable=True),
    sa.Column('listed on FINANCIAL CONSUMER ALERT LIST by Bank Negara Malaysia', sa.TEXT(), nullable=True),
    sa.Column('Combined_Remarks', sa.TEXT(), nullable=True)
    )
    op.create_table('alert-list',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('years', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('combined_remarks', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
